### ISSUE TITLE
Let's create the second issue.

### ISSUE THREAD

**Issue by cosmiclattes** [cosmiclattes/notifications-test#2]
This is the second issue.

**Comment by cosmiclattes** [comment]
Whats the issue here? How do we solve this?

**Comment by tumblingstone** [comment]
Is there something I can do to help out here ?

**Comment by cosmiclattes** [comment]
Yes you can definitely help out by triaging the issue here.

**Comment by cosmiclattes** [comment]
Let me try triaging it, yup I got lucky, its fixed.
